server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
        ###向注册中心上注册自己
      register-with-eureka: true
        ###是否需要从eureka上获取注册信息
      fetch-registry: true

spring:
  application:
    name: service-chat
  servlet:
    multipart:
      max-request-size: 1000Mb
      max-file-size: 1000Mb
  datasource:
    password: workhub_iwork
    tomcat:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      max-wait: 10000
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.11.24.136:1521:arltr
    username: workhub_iwork
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: hollykunge
    password: 123456
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          max-attempts: 3
          initial-interval: 2000ms
          enabled: true

  redis:
    port: 6379
    jedis:
      pool:
        max-idle: 200
        min-idle: 50
        max-active: 500
        max-wait: 200s
    host: 127.0.0.1
    timeout: 3000s
    password: 123456
#处理无用附件的定时任务时间
#每天凌晨两点
#deal_unused_file_job_cron: 0 0 2 * * ?
#来自ace-adimin通知新消息的消息队列名称
aceNoticeRabbitMqQueueName: noticeToChatService

mybatis:
  mapper-locations: classpath:mapper/*.xml
#是否显示控制台输出，1显示0不显示，生产环境配置0即可
showConsoleInf: 1
#处理历史消息的定时任务时间
#每月凌晨一点
deal_his_msg_job_cron: 0 0 1 1 * ?
#运行日志
logging:
  file: ${user.home}/logs/chat.log
#文件上传配置（用户级别）
#文件上传目录（最后要有斜杠）
file_save_path_group: C:/file-management-center/upload/group/

#增加ribbon超时连接
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false

auth:
  client:
    token-header: client-token
    id: service-chat
    secret: 123456
  serviceId: ace-auth
  user:
    token-header: Authorization
# logback日志配置
log:
  env:
    module: service-chat
#用户上传文件大小限制（单位M）
file_size_max: 500